# Generated by Django 2.1.7 on 2019-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0013_logdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicesettings',
            options={'verbose_name': 'Device location', 'verbose_name_plural': 'Device location'},
        ),
        migrations.RenameField(
            model_name='devicesettings',
            old_name='imei_code',
            new_name='deviceName',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='order',
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='bin_height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
