# Generated by Django 2.1.7 on 2019-11-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0014_auto_20191120_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='imei_code',
            new_name='deviceName',
        ),
    ]
