# Generated by Django 2.1.7 on 2019-11-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0015_auto_20191120_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdata',
            old_name='imei_code',
            new_name='deviceName',
        ),
    ]
