# Generated by Django 2.1.7 on 2019-12-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0016_auto_20191121_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='deviceName',
            new_name='dev_id',
        ),
        migrations.RenameField(
            model_name='devicesettings',
            old_name='deviceName',
            new_name='dev_id',
        ),
        migrations.RenameField(
            model_name='logdata',
            old_name='deviceName',
            new_name='dev_id',
        ),
    ]
